package modelo;
// Generated 17-nov-2022 17:49:20 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private BigDecimal ccodalu;
     private String cnomalu;

    public Alumnos() {
    }

	
    public Alumnos(BigDecimal ccodalu) {
        this.ccodalu = ccodalu;
    }
    public Alumnos(BigDecimal ccodalu, String cnomalu) {
       this.ccodalu = ccodalu;
       this.cnomalu = cnomalu;
    }
   
    public BigDecimal getCcodalu() {
        return this.ccodalu;
    }
    
    public void setCcodalu(BigDecimal ccodalu) {
        this.ccodalu = ccodalu;
    }
    public String getCnomalu() {
        return this.cnomalu;
    }
    
    public void setCnomalu(String cnomalu) {
        this.cnomalu = cnomalu;
    }




}


