package modelo;
// Generated 17-nov-2022 17:49:20 by Hibernate Tools 4.3.1



/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private long id;
     private String calle;
     private Long numero;
     private String poblacion;
     private String provincia;

    public Direccion() {
    }

	
    public Direccion(long id) {
        this.id = id;
    }
    public Direccion(long id, String calle, Long numero, String poblacion, String provincia) {
       this.id = id;
       this.calle = calle;
       this.numero = numero;
       this.poblacion = poblacion;
       this.provincia = provincia;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public Long getNumero() {
        return this.numero;
    }
    
    public void setNumero(Long numero) {
        this.numero = numero;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }




}


