package modelo;
// Generated 17-nov-2022 17:49:20 by Hibernate Tools 4.3.1



/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private long id;
     private String nombre;
     private String ape1;
     private String ape2;
     
     private Direccion direccion;


    public Profesor() {
    }

	
    public Profesor(long id) {
        this.id = id;
    }
    public Profesor(long id, String nombre, String ape1, String ape2) {
       this.id = id;
       this.nombre = nombre;
       this.ape1 = ape1;
       this.ape2 = ape2;
       
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApe1() {
        return this.ape1;
    }
    
    public void setApe1(String ape1) {
        this.ape1 = ape1;
    }
    public String getApe2() {
        return this.ape2;
    }
    
    public void setApe2(String ape2) {
        this.ape2 = ape2;
    }
    public Direccion getDireccion(){
        return this.direccion;
    }
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }



}


