CREATE OR REPLACE TYPE t_DIRECCION AS OBJECT
(
    TIPO VARCHAR2(2),
    NOMBRE VARCHAR2(100),
    NUMERO NUMBER(3)
);

CREATE OR REPLACE TYPE t_ALUMNO AS OBJECT
(
    NMATRICULA number(4),
    CURSO varchar2(9),
    FEC_NAC date,
    DIR t_DIRECCION,
    MEMBER FUNCTION fEDAD RETURN number,
    MEMBER PROCEDURE spVERDATOS
);
CREATE OR REPLACE TYPE BODY t_ALUMNO AS
MEMBER FUNCTION fEDAD RETURN number IS
    ED NUMBER;
    BEGIN
        ED := TO_CHAR(SYSDATE,'yyyy') - TO_CHAR(FEC_NAC,'yyyy');
        RETURN ED;
    END;
MEMBER PROCEDURE spVERDATOS IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE(CURSO||NMATRICULA||fEDAD());
    END;
END;

set serveroutput on;
declare
    a t_alumno;
begin
    a := t_alumno(null, null, null, null);
    dbms_output.put_line('La matrícula del alumno es ' || a.spVERDATOS);
end;

CREATE TABLE OBJETOS_ALUMNOS OF t_ALUMNO;
ALTER TABLE OBJETOS_ALUMNOS ADD CONSTRAINT PK_NMATRICULA PRIMARY KEY(NMATRICULA);

INSERT INTO OBJETOS_ALUMNOS VALUES(t_ALUMNO(1, null, null, null));
INSERT INTO OBJETOS_ALUMNOS VALUES(t_ALUMNO(2, '2 DAM', '09/01/2003', null));
INSERT INTO OBJETOS_ALUMNOS VALUES(t_ALUMNO(3, '1 DAM', '01/01/2000', null));

SELECT A.*, A.fEDAD() FROM OBJETOS_ALUMNOS A;

DELETE OBJETOS_ALUMNOS A WHERE A.fEDAD() IS NULL;


