
package relojdigital;

import java.util.Date;

public class AlarmaPanel extends javax.swing.JPanel {


    public AlarmaPanel() {
        initComponents();
    }
    
    public Alarma getSelectedValue(){
        Date fecha = (Date)spinAlarma.getValue();
        boolean activa = cbxActiva.isSelected();
        Alarma alarma = new Alarma(fecha, activa);
        return alarma;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spinAlarma = new javax.swing.JSpinner();
        cbxActiva = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        spinAlarma.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));
        spinAlarma.setEditor(new javax.swing.JSpinner.DateEditor(spinAlarma, "hh:mm:ss"));

        cbxActiva.setText("Activar");

        jLabel1.setText("Hora:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxActiva)
                    .addComponent(spinAlarma, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinAlarma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxActiva)
                .addContainerGap(183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxActiva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner spinAlarma;
    // End of variables declaration//GEN-END:variables
}
