/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciosxml;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.*;
import javax.xml.transform.*;
import javax.xml.transform.dom.*;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.*;
import org.xml.sax.SAXException;


public class JFrameNuevoXML extends javax.swing.JFrame {

    static ArrayList<String> libros = new ArrayList<>();
    static ArrayList<String> paginas = new ArrayList<>();
    static DocumentBuilder builder;
    static Transformer transform;
    static Document doc;
    static Element raiz;
    static NodeList raizHijos;
    static NamedNodeMap atributos;
    static Element nodo;
    static Attr atributo;
    static DefaultTableModel tabla;
    
    public JFrameNuevoXML() {
        initComponents();
        tabla = (DefaultTableModel)tableLibros.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        txtNombreFichero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGenerarXML = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNumPaginas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLibros = new javax.swing.JTable();
        btnCargarXML = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generación/Lectura de documentos XML | Mario Ortiz Jibaja");

        jLabel1.setText("Título");

        btnInsertar.setText("Insertar libro");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Fichero");

        btnGenerarXML.setText("Generar XML");
        btnGenerarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarXMLActionPerformed(evt);
            }
        });

        jLabel3.setText("Nº pág.");

        tableLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Libro", "Núm. Páginas"
            }
        ));
        jScrollPane1.setViewportView(tableLibros);

        btnCargarXML.setText("Cargar XML");
        btnCargarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarXMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(88, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtNombreFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnInsertar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCargarXML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenerarXML, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnGenerarXML))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCargarXML)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        if (txtTitulo.getText() != null && txtTitulo.getText() != "") {
            libros.add(txtTitulo.getText());
        }
        if (txtNumPaginas.getText() != null && txtNumPaginas.getText() != "") {
            paginas.add(txtNumPaginas.getText());
        }        
        else{
            JOptionPane.showMessageDialog(null, "No se ha insertado ningún valor válido en \"Num Páginas\"");
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnGenerarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarXMLActionPerformed
        try{
            //  Creamos una instancia del parseador.
            builder = DocumentBuilderFactory.newInstance().newDocumentBuilder();
            //  Creamos un árbol DOM vacío.
            doc = builder.newDocument();
            //  Creamos el elemento root.
            raiz = doc.createElement("libros");
            doc.appendChild(raiz);         
            int contador = 0;
            for(String libro : libros){
                nodo = doc.createElement("libro");
                nodo.setTextContent(libro);
                nodo.setAttribute("numPaginas", paginas.get(contador));            
                contador++;
                raiz.appendChild(nodo);
            }
        } catch (ParserConfigurationException ex){
            JOptionPane.showMessageDialog(null, "ERROR DE PARSEO");
        }
        try {
           //   Creamos un Transformer para poder crear un documento XML.
           transform = TransformerFactory.newInstance().newTransformer();
           transform.setOutputProperty(OutputKeys.INDENT, "yes");
           //   Elegimos el DOC de origen para crear el XML.
           Source source = new DOMSource(doc);
           //   Determinamos el fichero destino para exportar el DOM XML.
           String nombreXML = "";
            if (txtNombreFichero.getText() != "" && txtNombreFichero.getText() != null) {
                nombreXML = txtNombreFichero.getText();
            }
            else{
                nombreXML = "libros.xml";
            }
           Result resultado = new StreamResult(new File(nombreXML));
           transform.transform(source, resultado);
        } catch (TransformerConfigurationException ex) {
            JOptionPane.showMessageDialog(null, "ERROR AL CREAR EL TRANSFORMER");
        } catch (TransformerException ex) {
           JOptionPane.showMessageDialog(null, "ERROR AL CREAR EL DOCUMENTO XML");
        }
        
    }//GEN-LAST:event_btnGenerarXMLActionPerformed

    private void btnCargarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarXMLActionPerformed
        tabla.setRowCount(0);
        String nombreXML = "";
        if ((!txtNombreFichero.getText().equals("")) && (txtNombreFichero.getText() != null)) {
            nombreXML = txtNombreFichero.getText();
        }
        else{
            nombreXML = "libros.xml";
        }
        try {
            builder = DocumentBuilderFactory.newInstance().newDocumentBuilder();
            doc = builder.parse(new File(nombreXML));
            raiz = doc.getDocumentElement();
            if (raiz.getNodeType() == Node.ELEMENT_NODE) {
                if (raiz.hasChildNodes()) {
                    raizHijos = raiz.getChildNodes();
                    for (int i = 0; i < 10; i++) {
                        Node raizHijo = raizHijos.item(i);
                        if (raizHijo instanceof Element) {
                            if (raizHijo.hasAttributes()) {
                                atributo = ((Element) raizHijo).getAttributeNode("numPaginas");
                                Object[] datos = {raizHijo.getTextContent(), atributo.getValue()};
                                tabla.addRow(datos);
                            }
                        }
                    }
                }
            }
            

            
        } catch (ParserConfigurationException ex) {
            JOptionPane.showMessageDialog(null, "ERROR: No se ha podido cargar el parseador para leer.");
        } catch (SAXException ex) {
            JOptionPane.showMessageDialog(null, "ERROR: No se ha podido leer el documento " + nombreXML + " ." );
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "ERROR: No se ha podido acceder al fichero.");
        }
    }//GEN-LAST:event_btnCargarXMLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevoXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevoXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevoXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevoXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameNuevoXML().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarXML;
    private javax.swing.JButton btnGenerarXML;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLibros;
    private javax.swing.JTextField txtNombreFichero;
    private javax.swing.JTextField txtNumPaginas;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
