package modelo;
// Generated 23-nov-2022 17:10:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private long id;
     private String nombre;
     private Set libros = new HashSet(0);

    public Persona() {
    }

	
    public Persona(long id) {
        this.id = id;
    }
    public Persona(long id, String nombre, Set libros) {
       this.id = id;
       this.nombre = nombre;
       this.libros = libros;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getLibros() {
        return this.libros;
    }
    
    public void setLibros(Set libros) {
        this.libros = libros;
    }
    
    public int getNumlibros(){
        return libros.size();
    }




}


