package modelo;
// Generated 23-nov-2022 17:10:03 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String username;
     private String password;

    public Usuarios() {
    }

	
    public Usuarios(String username) {
        this.username = username;
    }
    public Usuarios(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


